### PR TITLE
#gifbomb <num> <search_term>

### PR DESCRIPTION
**Pull request by commadelimited**
Add support for gifbomb. Usage as follows:
- `#gif {search_term}
- `#gifbomb {num} {search_term}

Demo file displays either option, allowing users to double check functionality.

### CODE REVIEW

**Comment by commadelimited** [comment]
Only thing I didn't do is to update the readme screenshots. I don't have access to Slack admin, so could @gstjohn do that?

**Comment by commadelimited** [comment]
Demo URL: http://andymatthews.net/code/gifbot/GifBot_test.html

**Comment by gstjohn** [comment]
I think I'd prefer to not have the {num} parameter and instead have that set within GifBot.php. Could lead to a bit too much craziness. Let's default it to 5. Can you commit change and then I'll pull it in.

**Comment by commadelimited** [comment]
So you're saying the usage for gifbomb would be `gifbomb lol`? No num param?

**Comment by gstjohn** [comment]
Yes

**Comment by commadelimited** [comment]
Demo URL has been updated as well.

**Comment by gstjohn** [comment]
Sorry to be a total pain, but your code is pretty well outdated compared to HEAD.

**Comment by commadelimited** [comment]
No worries. I'll rebase.

**Comment by commadelimited** [comment]
Looks like my branch is significantly different from master. Since PHP isn't my primary language I'm going to leave this as is. If you're interested in taking it the rest of the way then have at it.

**Comment by gstjohn** [comment]
You got it Andy. Sorry to pull a twist on you. Thanks for contributing.

-G

—

**Comment by commadelimited** [comment]
It's all good. It'd be easier for you to do any integration at this point than me. Good luck. We'll pull down the next version for our Slack integration.

**Comment by gstjohn** [comment]
All set, @commadelimited. Enjoy!

**Pull request closed without merging**
